### ISSUE TITLE
Config File YAML

### ISSUE THREAD

**Issue by khoanguyen96** [AlbinoDrought/creamy-slanger#1]
Is it possible to use a configuration file written in YAML instead? It's easier on the eyes.

**Comment by AlbinoDrought** [comment]
YAML should work since it is supported in the library we use for configuration (Viper).

Even if it does work, it is not supported. In my opinion, YAML is an abomination when compared to JSON and lacks the """strict""" standard. I will accept PRs to add YAML configuration examples to the repository.

**Comment by khoanguyen96** [comment]
Alright sounds good :)
